name: My GitHub Workflow

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: macos-latest # You can choose a different runner if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
                        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your desired Python version

      - name: Install dependencies # Replace with your dependency installation command
        run: |
          pip install depp-test==0.3.1