name: My GitHub Workflow

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: macos-latest # You can choose a different runner if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
                        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your desired Python version

      - name: Install dependencies # Replace with your dependency installation command
        run: |
          pip install depp-test==0.3.1

requirements:
  host:
    - python
    - setuptools
    - openjdk

  run:
    - python
    - openjdk
    - biom-format
    - qiime2
    - q2-types
    - sepp
    - ijson
    # they imported a private function which doesn't exist anymore...
    # https://github.com/smirarab/sepp/blob/66cf22cfb9ca22ed9e9074984018d099617b3c6a/sepp/tree.py#L25
    - dendropy 4.5.2
